package dev.ranzlappen.gadget.buildlogic

import org.gradle.api.Project
import org.gradle.api.artifacts.VersionCatalog
import org.gradle.api.artifacts.VersionCatalogsExtension
import org.gradle.kotlin.dsl.getByType

/**
 * Accessor that lets convention plugin source code reach the `libs` version
 * catalog declared in `gradle/libs.versions.toml`.
 *
 * Inside a module's own `build.gradle.kts`, the `libs` accessor is
 * auto-generated by Gradle from the `versionCatalogs` declaration in the
 * settings file. Inside a plugin's *compiled* source code we don't have
 * that compile-time accessor, so we look the catalog up by name at runtime
 * via `VersionCatalogsExtension`.
 *
 * Usage:
 *
 *     dependencies {
 *         add("implementation", libs.findLibrary("hilt-android").get())
 *     }
 */
internal val Project.libs: VersionCatalog
    get() = extensions.getByType<VersionCatalogsExtension>().named("libs")
